server:
  port: 10000

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/robo_world_db
    username: root
    password: pass
  security:
    jwt:
      time-to-live: 3600000 #1 hour -> ms
      secret: jwtTokenSecret
      refresh-token:
        time-to-live: 36000000 #10 hours -> ms